version: "3.9"
services:
  app:
    build: ./StudentCoursesRestAPI/
    ports:
      - target: 8080
        published: 8084
        protocol: tcp
    environment:
      - MYSQL_SERVER=172.17.0.2
  dbserver:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
      - MYSQL_USER=directdevops
      - MYSQL_PASSWORD=directdevops

