version: "3.9"
services:
  app:
    build: ./StudentCoursesRestAPI/
    ports:
      - target: 8080
        published: 8084
        protocol: tcp
    environment:
      - MYSQL_SERVER=dbserver
    networks:
      - my-net
    depends_on:
      - dbserver
  dbserver:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
      - MYSQL_USER=directdevops
      - MYSQL_PASSWORD=directdevops
    networks:
      - my-net2
networks:
  my-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/16
  my-net2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16